version: 0.2

phases:
  build:
    commands:
      # Build Docker image
      - echo Building Docker image...
      - docker build -t myapp:latest .

      # Log in to ECR Public
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin public.ecr.aws/b5l5p7r2

      # Tag and push Docker image to ECR Public
      - echo Pushing Docker image to ECR Public...
      - docker tag myapp:latest public.ecr.aws/b5l5p7r2/myapp:latest
      - docker push public.ecr.aws/b5l5p7r2/myapp:latest
