version: 0.2

phases:
  build:
    commands:
      # Build Docker image
      - echo Building Docker image...
      - docker build -t aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b5l5p7r2/myapp:latest .
      
      # Log in to ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b5l5p7r2

      # Push Docker image to ECR
      - echo Pushing Docker image to ECR...
      - docker push aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b5l5p7r2 /myapp:latest
